CREATE TABLE IF NOT EXISTS users (
    id SMALLINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL ,
    last_name VARCHAR(400)
);

CREATE TABLE IF NOT EXISTS tasks (
    id SMALLINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL ,
    description VARCHAR(400) NOT NULL,
    priority BOOLEAN,
    user_id SMALLINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);